<a href="https://colab.research.google.com/github/PKInnovate/first-demo/blob/main/00_pythorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Dundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
# To get tensor back as python int
scalar.item()

7

In [ ]:
 # Vector
 vector = torch.tensor([7, 7])
 vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9, 4],
                        [2, 4, 5, 4],
                        [2, 4, 5, 4]],
                        [[1, 2, 3, 4],
                        [3, 6, 9, 4],
                        [2, 4, 5, 4],
                        [2, 4, 5, 4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 4],
         [2, 4, 5, 4],
         [2, 4, 5, 4]],

        [[1, 2, 3, 4],
         [3, 6, 9, 4],
         [2, 4, 5, 4],
         [2, 4, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 4, 4])

In [ ]:
TENSOR[1][1][0]

tensor(3)

### Random tensors
Why Random tensors?

Random tensors are important abecause the way manu neural networks
learn is thath they start with tensors full of
random numbers and then adjust those random numbers to better
represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
print(random_tensor)


tensor([[0.8938, 0.4414, 0.4094, 0.2711],
        [0.8398, 0.2711, 0.3812, 0.6670],
        [0.7662, 0.9919, 0.8608, 0.0274]])


In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color change
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and Ones

In [ ]:
# Create a tenspr of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 2, 2))
ones

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [ ]:
ones.dtype

torch.float32

# Create a range of tensors and tensor-like

In [ ]:
# Use torch.arange()
oen_to_ten = torch.arange(1,11,1)
print(oen_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


### Tesnsor datatypes

*Note*: Tensor datatypes is one of the 3 big errors we'll run into with PyTorch & deep learning:
1. Tensor not right datatype.
2. Tensor not right shape.
3. Tensor not right device

In [ ]:
# Flote 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
 float_16_tensor = float_32_tensor.type(torch.float16)
 float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting  information from tensors

1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape. - to get shape from a tensor, can use `tensor.shape`
3. Tensor not right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor

some_tesnor = torch.rand(3, 4)
some_tesnor

tensor([[0.7220, 0.7935, 0.5032, 0.1873],
        [0.3780, 0.9672, 0.2093, 0.2803],
        [0.2858, 0.8417, 0.4354, 0.6153]])

In [ ]:
# Find the details of the tensor
print(some_tesnor)
print(f"Datatype of tensor: {some_tesnor.dtype}")
print(f"Shape of tensor: {some_tesnor.shape}")
print(f"Device tensor is on: {some_tesnor.device}")


tensor([[0.7220, 0.7935, 0.5032, 0.1873],
        [0.3780, 0.9672, 0.2093, 0.2803],
        [0.2858, 0.8417, 0.4354, 0.6153]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tesnsor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
# Try out PytTorch in-nuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication
Two main ways of multiplying tensors in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules for matrix multilpllication:
1. The **inner dimentions** must match.
* (3,2) @ (3, 2) won't work
* (2, 3) @ (3,2) will work
* (3, 2) @ (2, 3) will work
* (3, 3) @ (3, 3) will work

2. The resulting matrix has the shape of the **Outer dimentions**:
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2, 3) -> (3,3)


In [ ]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.21 ms, sys: 0 ns, total: 1.21 ms
Wall time: 2.62 ms


In [ ]:
%%timeit
torch.matmul(tensor, tensor)

5.38 µs ± 1.7 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### One of the common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.matmul(tensor_A, tensor_B) # torch.mm is same as torch.matmul

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues we can manipulate the shape of our tensor using:
1. **Tanspose** switch the dimentions of a given tensor.


In [ ]:
tensor_B.T
print(tensor_B.T.shape)


torch.Size([2, 3])


In [ ]:
result = torch.matmul(tensor_A, tensor_B.T)
print(result)
print(result.shape)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
torch.Size([3, 3])


In [ ]:
result[2][2]

tensor(117)

### Finiding the min, max, mean, sum, etc (tensor aggregation)


In [ ]:
# Create a tensor
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean()function requires a tensor f foalt32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in the tnesor that has the minimum value with argmin () -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Find the position in the tensor that has maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping , staccking, squeezing and unsqueezing the tensors

* **Reshaping** - reshapes an input tensor to a defined shape.
* **View** - Return a view of an input tnesor of certain shape but keep the same memoryas the original tensor.
* **Stacking** - Combine multiple tensors on top of each other (vstack) or side-by-side(hstack).
* **Squeeze** - revoes all '1' dimention from the tensor.
* **Unsqueeze** - add a '1' diemsion to target tensor.
* **Permute** - Return a view of the input with dimensions ermuted(swaped) in a certain way.


In [ ]:
# Lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
 # Change the view
 z = x.view(1, 9)
 z, z.shape, z.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.Size([1, 9]))

In [ ]:
# Chinging z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape, x.size()

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]),
 torch.Size([9]))

In [ ]:
# torch.squeeze() -> removes all single dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# torch.unsquueeze() -> adds a singe dimentiion to a target tensor at a specipic dim
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# torch.permute -> rearranges the dimentsions of the target tensor in a speified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]


# permute the original tensor to rearrange the azis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_permuted

tensor([[[0.2814, 0.4190, 0.6212,  ..., 0.4646, 0.1503, 0.0832],
         [0.5224, 0.6095, 0.7684,  ..., 0.9607, 0.0708, 0.2735],
         [0.6043, 0.4311, 0.3126,  ..., 0.6854, 0.7327, 0.2262],
         ...,
         [0.6145, 0.0617, 0.6758,  ..., 0.0402, 0.8619, 0.6240],
         [0.1395, 0.3760, 0.2522,  ..., 0.9188, 0.5108, 0.3167],
         [0.8127, 0.2757, 0.1086,  ..., 0.0507, 0.0851, 0.3034]],

        [[0.3581, 0.0441, 0.3894,  ..., 0.4247, 0.7696, 0.6996],
         [0.6251, 0.0519, 0.3047,  ..., 0.5246, 0.2966, 0.2310],
         [0.9200, 0.5350, 0.2549,  ..., 0.4902, 0.3190, 0.5617],
         ...,
         [0.7920, 0.3319, 0.8043,  ..., 0.9792, 0.9039, 0.6832],
         [0.8509, 0.3850, 0.6227,  ..., 0.3942, 0.3575, 0.5264],
         [0.4847, 0.7945, 0.2471,  ..., 0.9056, 0.9038, 0.3321]],

        [[0.6340, 0.9035, 0.6267,  ..., 0.9277, 0.0346, 0.4238],
         [0.9469, 0.4167, 0.6235,  ..., 0.6850, 0.9991, 0.8863],
         [0.4774, 0.1124, 0.3003,  ..., 0.3499, 0.9034, 0.

In [ ]:
x_original

tensor([[[0.2814, 0.3581, 0.6340],
         [0.4190, 0.0441, 0.9035],
         [0.6212, 0.3894, 0.6267],
         ...,
         [0.4646, 0.4247, 0.9277],
         [0.1503, 0.7696, 0.0346],
         [0.0832, 0.6996, 0.4238]],

        [[0.5224, 0.6251, 0.9469],
         [0.6095, 0.0519, 0.4167],
         [0.7684, 0.3047, 0.6235],
         ...,
         [0.9607, 0.5246, 0.6850],
         [0.0708, 0.2966, 0.9991],
         [0.2735, 0.2310, 0.8863]],

        [[0.6043, 0.9200, 0.4774],
         [0.4311, 0.5350, 0.1124],
         [0.3126, 0.2549, 0.3003],
         ...,
         [0.6854, 0.4902, 0.3499],
         [0.7327, 0.3190, 0.9034],
         [0.2262, 0.5617, 0.0835]],

        ...,

        [[0.6145, 0.7920, 0.9446],
         [0.0617, 0.3319, 0.5211],
         [0.6758, 0.8043, 0.1017],
         ...,
         [0.0402, 0.9792, 0.4190],
         [0.8619, 0.9039, 0.1258],
         [0.6240, 0.6832, 0.5324]],

        [[0.1395, 0.8509, 0.6586],
         [0.3760, 0.3850, 0.5362],
         [0.

## Indexing

**Indexing** with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index
x[0][0][0]


tensor(1)

In [ ]:
x[0 , 0, :] # ':' -> list all the data in the dim


tensor([1, 2, 3])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])